/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2020-10-26 11:58:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import controllers.Mensagem;

public final class carteirarest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controllers.Mensagem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"estilo.css\" />\r\n");
      out.write("<title>Lista de Carteiras</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"corpoPagina\">\r\n");
      out.write("\t<div class=\"tableResult\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<!-- (READ) Tabela para listar os dados lidos no Banco de Dados -->\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>id Cliente</th>\r\n");
      out.write("\t\t\t\t\t<th>Nome</th>\r\n");
      out.write("\t\t\t\t\t<th>lucro Esperado</th>\r\n");
      out.write("\t\t\t\t\t<th>Prejuizo Maximo</th>\r\n");
      out.write("\t\t\t\t\t<th>Perfil de Investimento</th>\r\n");
      out.write("\t\t\t\t\t<th>Ações</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody id=\"corpoTabela\">\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form1\">\r\n");
      out.write("\t\t<!-- (CREATE) Formulário para cadastro de novas Carteiras -->\r\n");
      out.write("\t\t<form method=\"POST\" action=\"carteirarest\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"nome\" placeholder=\"Nome\" /> <input\r\n");
      out.write("\t\t\t\ttype=\"number\" name=\"lucro_esperado\" placeholder=\"Lucro Esperado\" />\r\n");
      out.write("\t\t\t<input type=\"number\" name=\"prejuiso_maximo\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Prejuizo Maximo\" /><select name=\"perfil_investimento\">\r\n");
      out.write("\t\t\t\t<option>Perfil de Investimento</option>\r\n");
      out.write("\t\t\t\t<option>Conservador</option>\r\n");
      out.write("\t\t\t\t<option>Moderado</option>\r\n");
      out.write("\t\t\t\t<option>Agressivo</option>\r\n");
      out.write("\t\t\t</select> <input type=\"submit\" value=\"Adicionar\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mensagem\" id=\"msg\">\r\n");
      out.write("\t\t<!-- Espaço reservado para menságens do sistema que desaparecem após 3 segundos -->\r\n");
      out.write("\t\t");

			if (!Mensagem.getMensagens().isEmpty())
			while (!Mensagem.getMensagens().isEmpty())
				out.print("<p>" + Mensagem.getMensagem() + "</p>");
		else
			out.print("<p>Mensagens do sistema:</p>");
		
      out.write("\r\n");
      out.write("\t\t<script>setTimeout(() => {document.getElementById(\"msg\").style.display=\"none\"}, 3000);</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"carteirarest.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
